#!groovy
pipeline {
    agent any

    environment {
        NODE_VERSION = 'v10.15.0'
        NODE_MIRROR = 'https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/'
    }
    stages {
        stage('Build') {
            steps {
                nvm('version': env.NODE_VERSION) {
                    sh "make docker-build"
                }
            }
        }
    }
}
