#!groovy
pipeline {
    agent any

    environment {
        NODE_VERSION = '12.16.2'
        NODE_MIRROR = 'https://mirrors.tuna.tsinghua.edu.cn/nodejs-release/'
    }
    stages {
        stage('Build') {
            steps {
                nvm('version': env.NODE_VERSION) {
                    sh(script: "make docker-build", label: "docker")
                }
            }
        }
    }
}
