POST http://localhost:3000/ping
Content-Type: application/json
X-Request-ID: 08be03d1-1678-4a3d-bd52-dc956d94f076

{}

###
POST http://localhost:3000/run_task
Content-Type: application/json
X-Request-ID: 1be6157f-481c-4b22-9d3d-f455bc333742

{}
